### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by 6graNik** [rempl/rempl-cli#2]
Hello, I was trying to use webpack-runtime-analyzer.

Which need rempl-cli for running rempl via cmd.

Got strange error.

![image](https://cloud.githubusercontent.com/assets/6370221/24249047/d95f2b7a-0fe2-11e7-8301-4c77860d2465.png)

I have socket.io-client installed global such as rempl-cli.

![image](https://cloud.githubusercontent.com/assets/6370221/24249184/57e1d506-0fe3-11e7-8409-a09fbd4f70fb.png)

I tried to figure out whats wrong by myself but unfortunately failed =(

**Comment by lahmatiy** [comment]
Hi, @6graNik!
Yep, there is an issue with updated `socket.io-client`. We are planning a bunch of releases (rempl, rempl-cli and webpack-runtime-analyzer) later today or tomorrow, that should fix the issue along with other improvements. Sorry for inconvenient.

**Comment by 6graNik** [comment]
@lahmatiy Thanks for answer. I also want to ask you about remote dev tools.

May be I misunderstood a bit, correct me if I am wrong, but in your speech on HolyJS u said, that there is a way(may be plugin already), to use remote developer tools via remlp.

Did you mean, that we have ability to build it with rempl, or that it's already build? 

I asking because can't find it anywhere, but may be it is my goggling skills.

I am really exiting to use it for remote debugging mobile, right now debugging iOS devices is real pain. 

P.S. Also maybe u just freeze socket-io.client version for future?

**Comment by lahmatiy** [comment]
`rempl`, `rempl-cli` and `webpack-runtime-analyzer` has been updated. Issue should be fixed. Also new version of `webpack-runtime-analyzer` has an integrated rempl server now, so it's getting much easier to start using it (see [release notes](https://github.com/smelukov/webpack-runtime-analyzer/releases/tag/v1.2.0)).

> Did you mean, that we have ability to build it with rempl, or that it's already build?

Rempl is platform for building custom tools (like `webpack-runtime-analyzer` or [conponent-inspector](https://github.com/lahmatiy/component-inspector)) with remote access to inspecting process. It doesn't relate with browser's developer tools, but tools built on rempl can be ran in that kind of tools. So it mostly about ability to build tools with rempl.

Maybe I misunderstand you. Anyway that kind of questions should be posted in rempl issues.
